# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-22 04:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0003_auto_20170521_2107'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VideoManager',
        ),
        migrations.AddField(
            model_name='video',
            name='image_path',
            field=models.CharField(blank=True, default='/static/ang/assets/images/nature/4.jpg', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='name',
            field=models.CharField(max_length=220, null=True),
        ),
    ]
