# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-22 05:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0004_auto_20170522_0437'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='image_path',
        ),
        migrations.AddField(
            model_name='video',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
